In [16]:
from sklearn.datasets import load_iris
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset
iris = load_iris()

# Create DataFrame
df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# Plot
df['petal length (cm)'].plot()

# Title
plt.title('Petal Length (cm)')

# Show graph
plt.show()



[1 3 2]
Array is of type: <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  float64
Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]
Array created using passed tuple:
 [1 3 2]
An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
A random array:
 [[0.86741273 0.73726408]
 [0.66175535 0.00114809]]
inA sequential array with steps of 5:n [ 0  5 10 15 20 25]
nA sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Histogram
x = np.random.randn(1000)
plt.hist(x)
plt.show()

# Scatter Plot
a = np.random.random(100)
b = np.random.random(100)
plt.scatter(a, b)
plt.xlabel('a')
plt.ylabel('b')
plt.show()

# Bar Chart
languages = ['Java', 'Python', 'PHP', 'JavaScript', 'C#', 'C++']
popularity = [22.2, 17.6, 8.8, 8, 7.7, 6.7]
plt.bar(languages, popularity)
plt.title('Programming Language Popularity')
plt.xlabel('Languages')
plt.ylabel('Popularity')
plt.show()
plt.barh(languages, popularity)
plt.title('Programming Language Popularity')
plt.xlabel('Languages')
plt.ylabel('Popularity')
plt.show()

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

# Convert to DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)

# Print dataset
print(df)

# Line Plot
plt.plot(df['sepal length (cm)'], df['sepal width (cm)'])
plt.xlabel("Sepal Length (cm)")
plt.ylabel("sepal width (cm)")
plt.title("Sepal Length vs Petal Length")

# Scatter plot is better for this dataset. This is just to demonstrate implementation



